### ISSUE TITLE
Where does this data come from?

### ISSUE THREAD

**Issue by blester125** [nxs5899/Named-Entity-Recognition_DeepLearning-keras#2]
Hello I am curious where the data in this repo comes from? It appears to be News data but is it from CONLL2003? Ontonotes? Somewhere else?

Thanks for the clarification.

**Comment by SaschaHeyer** [comment]
https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus

**Comment by blester125** [comment]
Thanks!
